### ISSUE TITLE
Pricing logic changes to complement the official API

### ISSUE THREAD

**Issue by pm5k** [Kyusung4698/PoE-Overlay#13]
Hey,

I wanted to raise this, but in case you are already aware or planning something similar please close this issue. 

**The problem:**

Currently the way your checker works even on big ticket items it can return a price average that does not match what the price range is at all. For example I tested it on a five linked Coming Calamity chest and it’s value IRL is anywhere from 10 to 25 chaos. Your price return came up with 1 chaos. That’s a massive difference. 

Most other items that are rare in my sell tab that have potential to fetch 5-10c are being priced under 1 chaos. 

**My Suggestion**

Allow league selector - SSF, SOFTCORE, HC, that influences prices greatly. I could not find this beyond just - Metamorph, I think. 

For unique pricing - you should try to add (if not already there) the total number of sockets as “minimum” and number of links as “minimum” in the API search. Then mod rolls from my item as minimum values too. Add the option to round those down before searching. What this does is provides a contextual floor for the search. If I have a unique ring that can roll 10-30 cold res and mine  is at 15, your search should never bother looking at similar uniques that are below 15. However if my rolls are 16/17/18 it can be less likely that I’ll find those numbers as a floor, therefore an option to search for 15 as a base floor value would cover my roll +- 2/3 values. 

For rare lookups this is a bit trickier and more nuanced. You firstly should consider allowing people to add (or maybe even adding yourself) a list of desirable mods that get prioritised one the search. Then when an item is looked up, you can begin a search like this:

1: are there items matching my item in all mods and between their floor and ceiling values?

2: if not, does it match the most desireable and popular mods?

3: if not, does it match at least 3 top rolled mods?

4: if not - could not determine price. 

5: for all other YES answers - show min/max/mean prices and if possible - time the item spent being listed. (Helps determine sellability if you have access to this data at all)

I hope this is useful.

**Comment by JusKillmeQik** [comment]
Instead of implementing logic yourself for rare items, you can use www.poeprices.info

They have a very simple api that gives a good estimate of rare item value based on affixes, it even returns  a confidence score. You just call https://www.poeprices.info/api?l=Metamorph&i=
with Base64 encoded data of the item at the end.

TradeMacro used it and I highly recommend adding it to your tool. It could be as simple as adding the price estimate someone in your overlay, or you could get fancy and highlight affixes that have a high effect. I know people have requested you highlight high tier affixes (which is hard since GGG doesn't provide it), but instead you could just highlight affixes that affect the market price (which will often be high tier) and will be returned by the api for you.

Let me know if you'd like more help with the api call. I look forward to the improvements you're making.

**Comment by Kyusung4698** [comment]
> Instead of implementing logic yourself for rare items, you can use [www.poeprices.info](http://www.poeprices.info)
> 
> They have a very simple api that gives a good estimate of rare item value based on affixes, it even returns a confidence score. You just call https://www.poeprices.info/api?l=Metamorph&i=
> with Base64 encoded data of the item at the end.
> 
> TradeMacro used it and I highly recommend adding it to your tool. It could be as simple as adding the price estimate someone in your overlay, or you could get fancy and highlight affixes that have a high effect. I know people have requested you highlight high tier affixes (which is hard since GGG doesn't provide it), but instead you could just highlight affixes that affect the market price (which will often be high tier) and will be returned by the api for you.
> 
> Let me know if you'd like more help with the api call. I look forward to the improvements you're making.

Thank you for your inside. I indeed do not plan on developing a price prediction. So poeprices.info comes in handy. I'll look into it!

This issue will be closed in favor of #178
