### ISSUE TITLE
Mods with rolls less than 1 fail to parse/search correctly

### ISSUE THREAD

**Issue by joe7dust** [Kyusung4698/PoE-Overlay#237]
Example: 0.4% spell dmg leeched as mana during flask effect = engine tried to use 0 to 0 min/max and you can see this by control clicking on data not found. Once you expand it to 0.4 to 5+ on the site you'll see plenty results.

edit: Also, the mod Seething is incorrectly parsed as Bubbling. (tries to search % instant effect instead of the actual text of Instant Recover (and on % required))

**Comment by Kyusung4698** [comment]
## 0.5.17 (2020-02-16)

- update modifier range clamp function to reset to 0 (#237)

Modifing values with decimals should now reset to 0 instead of the pre-scroll value.

Also could you provide some screenshots showing the mismatched mod `Seething`. Thanks.

**Comment by joe7dust** [comment]
![untitled2](https://user-images.githubusercontent.com/18081903/75033545-c831d200-5470-11ea-8ede-77e9f3e33683.png)
![Untitled3](https://user-images.githubusercontent.com/18081903/75033550-cb2cc280-5470-11ea-9fe0-684593522844.png)

Still not fixed. You can see it is also ignoring my max slider settings, it should be putting in 999 not 0.

**Comment by Kyusung4698** [comment]
## 0.5.20 (2020-02-23)

- update stats data  
  - fix non negatable mods using it's matched predicate only (#237)
  - fix some unavailable translations because of mismatched predicates
- fix query using integers only (#237)

Thank you for your input. There was an issue regarding integers. Max range and decimals should now be respected. Also the mentioned mod should work now.
