### ISSUE TITLE
POE Overlay do not work if you're using GeForce Now to run POE

### ISSUE THREAD

**Issue by ZeroCool940711** [Kyusung4698/PoE-Overlay#278]
Hi there, I recently started using GeForce Now to play POE as it runs better there and notice that POE Overlay doesn't seems to work when POE is running inside GeForce Now, it makes sense as the window title is different from what you get when you run POE normally, the process and window name seems to be always `Path of Exile on GeForce NOW`, I have an autohotkey script for POE and I tried adding that window title to the conditions that I have there to specify that I want to run it only when POE is running and it does work so I think POE Overlay should also work with that, would appreciate if this could be done so me and other people like me who use GeForce Now can play POE and use POE Overlay.

**Comment by vadash** [comment]
Cant be done since poe overlay doesnt have access to clipboard info

**Comment by Kyusung4698** [comment]
> Cant be done since poe overlay doesnt have access to clipboard info

Yes, basically this. The program uses the clipboard info in order to parse the item data. NVIDIA Geforce Now does not share this information because it's not a fully functional VM. This is understandable as the core focus of their service is on performance and therefore it's highly customized to reduce network traffic. I don't think this will ever be possible.
