### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by GinoSpadaccino** [Kyusung4698/PoE-Overlay#317]
I have aero on but the screen turns black when I run the overlay
I use the run-without-gpu.bat file to manage but is there a way to prevent the problem in the first place?

**Comment by Kyusung4698** [comment]
The `run-without-gpu.bat` got removed with 0.6 update. I'm currently working on a different solution. 

Hardware acceleration may causes issues because the chrome version may not be compatible with the used hardware/ drivers. As there are finite possibilities of hardware/ drivers etc. the easiest way to solve this is by disabling the hardware acceleration. Another user with this problem disabled for example NVIDIA G-Sync to resolve his issues.

**Comment by Kyusung4698** [comment]
## 0.6.5 (2020-03-16)

- add hardware acceleration toggle as tray option (#329, #327)
