### ISSUE TITLE
Graphics bug mentioned in FAQ

### ISSUE THREAD

**Issue by yxbengt** [Kyusung4698/PoE-Overlay#327]
I get the blurry/buggy graphics, and found the solution to that in the FAQ
However, the file you ask me to run cannot be found anywhere. Where is "run-without-gpu.bat"?

And if anyone knows of a fix for the problem without turning off hardware acceleration I would be happy for that too.

**Comment by Kyusung4698** [comment]
The `run-without-gpu.bat` got removed with 0.6 update. I'm currently working on a different solution. 

Hardware acceleration may causes issues because the chrome version may not be compatible with the used hardware/ drivers. As there are finite possibilities of hardware/ drivers etc. the easiest way to solve this is by disabling the hardware acceleration. Another user with this problem disabled for example NVIDIA G-Sync to resolve his issues.

**Comment by Kyusung4698** [comment]
## 0.6.5 (2020-03-16)

- add hardware acceleration toggle as tray option (#329, #327)
