### ISSUE TITLE
"Clipboard was empty Please make sure the game is focused" problem

### ISSUE THREAD

**Issue by dydxo959** [Kyusung4698/PoE-Overlay#333]
Cannot use this program becuz of this comment even in 0.6.4 version-setup.

I'm using poe kakao.ver(korean), and korean keyboard.

Every command didnt work.

If you need more information to solve this problem, plz comment.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Unfortunately i'm unable to download the Kakao version of the game - this always results in a 403 Forbidden error. Is this client geo restricted? 

I've changed my keyboard layout to Korean and this does not seem to be the issue. I assume it's related to the client which i'm unable to test because i can't install it. 

Can you try a manually copy of the item `CTRL + C` and then using any command. Does this work?

I'm looking forward to your response!

**Comment by dydxo959** [comment]
running the tool as administrator is the answer.

I appriciate for advice.


your program is really faster and comfortable than trademacro, thx to making this program

**Comment by dydxo959** [comment]
should i close this issue?

**Comment by Kyusung4698** [comment]
> should i close this issue?

I'll close it. I will also add a requiredAdministrator to ensure the program has the correct rights with the next version.

**Comment by Kyusung4698** [comment]
## 0.6.5 (2020-03-16)

- add requestExecutionLevel highest (#333)
