### ISSUE TITLE
Please do not force the app to run in administrator mode, it is bad design and a security risk to users

### ISSUE THREAD

**Issue by Cephel** [Kyusung4698/PoE-Overlay#361]
Title. There is no valid reason to have it run in admin mode. At the very least you should leave that choice up to users.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Security is important to me and therefore i'll try to answer this adequate. 

Admin mode is not requested but highestAvailable. Why? Because several issue were caused by insufficient rights (accessing clipboard data, sending input to poe which had been started with a higher security level). By using highestAvailable instead of requireAdministrator i make sure my app has at least equal permissions as poe. This also means you could run this tool with an non administrator account.

Regarding security. My app is signed using my official code signing certificate. This means my app can not be altered without destroying the signature. This ensures no one can release a version of this tool without my certificate. If you don't trust me you should not be using this software.

Please let me know if you have any further question.

Best regards

**Comment by Cephel** [comment]
Hi thanks for the answer.

Unfortunately `highestAvailable` will elevate permissions if the user is on an administrator account, which is almost every single person playing games on Windows.

Furthermore, `highestAvailable` will FORCE said elevation, as it is impossible to retain a limited permission set with it set.

> accessing clipboard data
This does not require an elevated permission to the best of my knowledge and if it does, it's an anti-pattern to bypass this security feature to begin with, as per [this link](https://docs.microsoft.com/en-us/windows/win32/dataxchg/about-the-clipboard)

> ending input to poe which had been started with a higher security level
This is a user error as PoE should not be started with elevated permissions anyways.

**Comment by vadash** [comment]
How about this: start in admin mod by default and add setting that allow user to without elevation as well ?

**Comment by HamishBlank** [comment]
> How about this: start in admin mod by default and add setting that allow user to run without elevation?

This is what other POE 3rd party apps do, not sure if they use escalation for the same reasons though.

**Comment by Cephel** [comment]
> How about this: start in admin mod by default and add setting that allow user to run without elevation?

No, the app should launch in unelevated mode by default with an opt-in option for admin mode for compatibility issues.

Really though, anyone that needs to fix compatibility by admin mode, can do so by hitting the checkbox via Windows as well. I'm not sure why this even needs to be an option.

**Comment by Kyusung4698** [comment]
## 0.6.11 (2020-03-24)

- update keyboard empty error to include you may need to start with privileged rights
- remove requestedExecutionLevel from manifest
