### ISSUE TITLE
Suggestion for pricing range & certain mods where entry should be in max not min

### ISSUE THREAD

**Issue by Lokeras** [Kyusung4698/PoE-Overlay#384]
Hi again,
Issue 1. There are item mods such as increased charges used, reduced item quantity and few other i believe where the number entry should go into max not min (you want to see items with values lower or equal to the one you have) New cluster jewel fits here too i think 8 passive cluster jewels are worth more than 10 or 12 passive ones.
Suggestion 2. Perhaps we dont need a range for pricing at all? say we use only low entry point?
Such search would show us items that are at least as good as the item that we have, people should be able to filter out of items that are MUCH better than the ones they have themselves, this way you are less likely to get no results and max rolls never get undermined when you get them.
hope that makes sense. feel free to clarify if something is unclear
p.s. really appreciate this project and how fast you implemented the fix for flask issue i have mentioned. thanks for your hard work

**Comment by nivh** [comment]
I also think it's a great idea to be able to choose if a specific attribute should only have min or max limit. specially I would like to see leveling items priced more correctly, by applying only max required level, and being able to control it. (example: if I want to price a req. level 30 item, I would limit the req. level to about 33 or 35 max [not min!] , so that people in those levels searching for similar properties would appreciate them, but I don't want to compare this property to higher levels, because of course they will out-match it)
