### ISSUE TITLE
Bug: Fast Tagging uses incorrect mouse position

### ISSUE THREAD

**Issue by vadash** [Kyusung4698/PoE-Overlay#386]
when u move mouse and click on histogram it will use wrong position
solution: save mouse coordinate when user press ctrl d

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is actually the current implementation. Are you using any zoom factors at windows? Or the actual overlay? Could you maybe provide a short gif. Thanks!

**Comment by EhhNahNoMouse** [comment]
Hi,
I think I'm also hitting this issue. Very often, when I try to fast tag an item, it will fail and instead trigger an ability/open chat. I'm in windowed full screen 1680x1050. vSync enabled, no zoom. 

I noticed that when I used windows step recorder that it has not failed once out of over 20 tries (usually fails well before that). Race condition maybe?

Gif of the bug in action!  https://gfycat.com/revolvingnearbrahmanbull

**Comment by sfenton3** [comment]
I just started using this program today. I have noticed that it works for a specific portion of the stash tab and other portions of it will cause the chat dialog to open and not set the price. Kinda weird, I think it is not recording the position of the cursor correctly. I am enjoying the program otherwise.

Win 10
1920x1080
Vsync enabled
no zoom
desktop
steam
