### ISSUE TITLE
Suggestion: Improve automated UI Polish Translation

### ISSUE THREAD

**Issue by Sathorn** [Kyusung4698/PoE-Overlay#405]
I have no idea where you get source for UI polish translation but it is garbage.
i.e main menu problems:
"Generał" in polish language refers to military rank general, not "general" or "generic" meaning. 
"komenda" it is not plural, should be "komendy"
"oceniać" - we rarely use it as inifinitive form, rather it should be "ocena przedmiotów"(item evaluation) or just "Ocena"
"Mapa" is singular, should be "Ocena Map" (map evaluation) or just "Mapy" plural
I believe there is more...

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The initial translations were made by Google Translate as i'm unfortunately not able to speak Polish. A awesome user of this tool has provided correct translations in the meantime. They will be available in the next update. Please see the updated file:

https://github.com/Kyusung4698/PoE-Overlay/blob/master/src/assets/i18n/polish.json

**Comment by Sathorn** [comment]
Can I participate and add my suggestions in this file?

**Comment by Kyusung4698** [comment]
> Can I participate and add my suggestions in this file?

Sure. Just download the file and attach it to this issue. I'll make sure it gets merged with the new version.

**Comment by Sathorn** [comment]
I created a fork, is it ok?

**Comment by Kyusung4698** [comment]
> I created a fork, is it ok?

Yes, of course. That'd be even better. Thanks! 👍

**Comment by Sathorn** [comment]
Ok I proposed my changes. Is it all possible translations? I couldn't find for instance map layout rating explanations from pop-ups. You know, Rating A,B and C

**Comment by Kyusung4698** [comment]
Hi, seems like I missed those. You can find the texts here:
https://github.com/Kyusung4698/PoE-Overlay/blob/master/src/app/modules/map/component/map-dialog/map-dialog.component.ts

I'll make them translatable. In the meantime you could provide the Polish values. 

The actual map bosses, items etc. are not translatable as these are provided by the poe wiki.

**Comment by Traf27** [comment]
> I have no idea where you get source for UI polish translation but it is garbage.
> i.e main menu problems:
> "Generał" in polish language refers to military rank general, not "general" or "generic" meaning.
> "komenda" it is not plural, should be "komendy"
> "oceniać" - we rarely use it as inifinitive form, rather it should be "ocena przedmiotów"(item evaluation) or just "Ocena"
> "Mapa" is singular, should be "Ocena Map" (map evaluation) or just "Mapy" plural
> I believe there is more...

@Sathorn 
Well I've written this **garbage** corrections to "**auto-translated**" translations made by @Kyusung4698 to start off gui translation, so hold your horses before you call someone's work garbage ok? Thats damn lot of work to go through all this keys you know... See original [auto-translated JSON](https://github.com/Kyusung4698/PoE-Overlay/blob/3f3aa9e5485fc3fc5eabe0d3da43ddffc60beb47/src/assets/i18n/polish.json) first. 
Ok I said what I had to. But ...

Lets get to some facts.

_See it in context of GUI_ - **compile code** and see how it looks like in ui interface.
Some phrases just does not match what you see.

- Mentioned "Komenda" would be "Komendy", but if you look inside this ui panel, you will find out that names get their content from the very same keyword which is .. the "name" same for tab and same for item.
```
        "day": "Do 24 godzin temu",
        "days": "3 Dni temu",
        "month": "Miesiąc temu",
        "months": "2 Miesiące temu",
        "day": "Ostatni dzień",
        "days": "Ostatnie 3 dni",
        "month": "Ostatni miesiąc",
        "months": "Ostatnie 3 miesiące",
```
 you see it when you pick time when the item was put on sale, so context is "when the auction was created",  "Ostatnie 3 miesiące" so it is translation variation.
Directly it was "Listing Max Age", so i called it "Data wystawienia" how you would construct statement which answer would be "Ostatnie 3 miesiące"?
- Moda is authentic statistick term, not Tryb
- sometimes you have to shorten terms, like in "Unikaty - sprawdź wszystkie modyfikatory" word "modyfikatory" would be cut off in half, and "mod" in slang which gamers use anyway, means the same
- sometimes you should make phrases more informative, like "Eksport statystyk", but where it will be exported? maybe you know that it is clipboard but not every gamer would know. Thus I  added it to translation
- It has to be something about item name being translated, because thats what happening. Suppose you have gui in english, but here you choose russian. When you check item price in poe, the popup will have item name translated, and rest will be english. (worse when its other language, becuase not all elements of popup are being translated
```
    "translate": "Wyceń przetłumaczony przedmiot",
    "translate-language": "Język przełumaczonego przedmiotu",
    "translate-settings": "Ustawienia tłumaczenia Wyceny"
    "translate": "Wyceń przedmiot",
    "translate-language": "Język wycenianego przedmiotu",
    "translate-settings": "Ustawienia Wyceny"
```

Some of your propositions are **better**, thanks, i had no clue how to make them work at 2.00am

**Comment by Sathorn** [comment]
My first comment "garbage" was about auto-translated text not yours... relax.
Anyway, I totally agree that the context and specific location of translated text in application shows what is really the meaning behind.
Btw "Komenda", the name of tab with only two commands: /hideout and /dnd - doesnt feel right.  I believe it is not reflecting exactly whats inside in polish language, even "Komendy" sounds just inapropriate.

**Comment by Traf27** [comment]
Sorry I got a little bit carried :)

**Comment by Traf27** [comment]
BTW I droped Issue with other missing keys for translation

**Comment by Kyusung4698** [comment]
## 0.6.10 (2020-03-22)

- add missing translations (#413)

Hi, i've added those missing translations. Is your fork read to be merged? If so please create a PR. Thanks! 🚀
