### ISSUE TITLE
ALT+TAB delay

### ISSUE THREAD

**Issue by KazumaIgarashi** [Kyusung4698/PoE-Overlay#455]
# 🐞 bug report

**Describe the bug**
After updating to 0.6.11, when switching from another window to the Path of Exile window by pressing ALT + TAB, there is a delay of a few seconds when switching is normal, but the operation is not accepted.
For example, you can't immediately press Enter to open a chat window.

I'm sorry that my English is not good.

## 🌍  Your Environment
- OS: Win10 x64
- Version: 0.6.11
- PoE: Steam 3.10.0/e English

**Comment by milesjavis** [comment]
+1 been experiencing the same issue

**Comment by barbarolucente** [comment]
Same here

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Seems like the Game is losing it's focus after Alt + Tabbing. I'm working on a fix. A quick workaround click anywhere into the game - should bring the focus back.

**Comment by Kyusung4698** [comment]
Hi, i've provide a [pre-release](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/v0.6.12). Please let me know if it's working now and i'll release it.

**Comment by KazumaIgarashi** [comment]
@Kyusung4698 
Thanks for the quick response, it's fixed!
Thank you very much.

**Comment by Kyusung4698** [comment]
> @Kyusung4698
> Thanks for the quick response, it's fixed!
> Thank you very much.

Awesome! Thanks for your feedback.

**Comment by MissingL-tter** [comment]
While the pre-release does indeed fix the focus loss.
It doesn't fix a related issue that I have found.

I have several application profiles setup for various games. Before today's patch, all of these behaved normally. While POE is focused my corsair POE profile is active, alt-tab out and it switches to my desktop profile.

After patching today not only did I experience the focus loss issue but ICUE can no longer detect that POE is the active application. I'm assuming this is related to the change that caused this issue.

**Comment by Niltah** [comment]
I can confirm the pre-release fix the focus loss issue for me too.

**Comment by Kyusung4698** [comment]
> While the pre-release does indeed fix the focus loss.
> It doesn't fix a related issue that I have found.
> 
> I have several application profiles setup for various games. Before today's patch, all of these behaved normally. While POE is focused my corsair POE profile is active, alt-tab out and it switches to my desktop profile.
> 
> After patching today not only did I experience the focus loss issue but ICUE can no longer detect that POE is the active application. I'm assuming this is related to the change that caused this issue.

Hi, the update 0.6.11 introduced keyboard support. In order to enable this i had to change my main window to be [focusable](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions). Otherwise i'm not able to capture the input/ focus. I'm not 100% happy with this solution but this also fixed some bugs on older OSs.

**Comment by MissingL-tter** [comment]
But any operation that needs to detect the currently focused application just breaks.
There are a lot of people using application profiles for POE (I don't need a flask macro when I'm on my desktop).

**Comment by Kyusung4698** [comment]
> But any operation that needs to detect the currently focused application just breaks.
> There are a lot of people using application profiles for POE (I don't need a flask macro when I'm on my desktop).

PoE is still the active/foreground window. Unless a item is priced.

**Comment by MissingL-tter** [comment]
Let me reinstall and I'll follow up. If that's the case outside applications shouldn't be affected, but from what I'm currently experiencing, they are.

**Comment by MissingL-tter** [comment]
**Without** PoE Overlay Running:
- Focused: `PoE`, Profile: `PoE`
- Alt Tab
- Focused: `Desktop`, Profile: `Desktop`
- Click/Alt Tab/Refocus PoE
- Focused: `PoE`, Profile: `PoE`

**With** PoE Overlay Running:
- Focused: `PoE`, Profile: `PoE`
- Alt Tab
- Focused: `Desktop`, Profile: `Desktop`
- Click/Alt Tab/Refocus PoE
- Focused: `PoE`, Profile: `Desktop`
   - System does not recognize that PoE is the currently focused application
   - The same thing happens if I open any of the overlay windows, basically any operation that causes PoE to lose focus
