### ISSUE TITLE
Ctr + D stuck at fetching entries.

### ISSUE THREAD

**Issue by maja0270558** [Kyusung4698/PoE-Overlay#458]
Idk what happen. Ctr + D stuck at fetching entries. Stop fetching entries and choose open in browser will show hint could not get next trade item at the bottom of browser. 
Game language: Traditional Chinese 
thanks your awesome tool image down below
https://imgur.com/a/Oiw7wp6

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems like a trade website error. Could you please translate the error at the trade page? Thanks!

**Comment by Halftune** [comment]
It seems like to be api block the request (result count is normal),
It has happened to me too. But dunno is the api's limit or caused by PoE-Overlay.
(test on 0.6.11)
![3](https://user-images.githubusercontent.com/29658265/77652959-0e1b1200-6faa-11ea-926b-45c77275ca25.PNG)
![image](https://user-images.githubusercontent.com/29658265/77653410-97cadf80-6faa-11ea-930a-e8a5c49aefeb.png)

api example url:
https://web.poe.garena.tw/api/trade/fetch/c6be4f3ed961b3f1b0c6cdedebcb05c9c92d09aab6eac10df1c3affec5bfea4b,4ff22ca2e9aae4dc738facfbbe232b5e1fb2d9514db4fb6ae8b901f3958c810e,615ad79cb99ecceeba2c7096025d932ec1590b81f909d3cc611c21ea6245c8df,8ffd97ac128f51ebde858e4654a799382a8f146467ad563b18341015d49b1900,96c2694d6aeb306dd8f737092b855ae573fba7b3b241e7aff2da5a6e8a271c4f,67d22fbf5542a7029f012e7dba015c8ceee90c8ac4da210e4f384a193f36fe18,d103cd5cc847b6d47d5f1b712d929671d5248af0921fc8a8c02b55b2e3bdc26f,9541ae8d223fac44d5e615f96948d89fedeebcd599be2e363545fe0c743c5841,072d8d388b4efac52d98e343469eae8922dbd267e7618d6af428b319adb73b57,2b742c3e584370439bb19e94a8bc80968dd20a2debbf8d165723c40e7e8abac5?query=8kOmjGuV

**Comment by Kyusung4698** [comment]
Hi, thanks for the follow up. I've increased the wait time between blocked requests. Maybe this fixed it.

**Comment by maja0270558** [comment]
Same on 0.6.15 
![image](https://user-images.githubusercontent.com/30047867/77842859-d25e9300-71c9-11ea-8262-5614b0cedb98.png)

**Comment by Kyusung4698** [comment]
This error is caused by poe.ninja. They do not support the garena league ids because those are in Chinese. The latest version has a fallback to fix this error. Also see this for further information #427
