### ISSUE TITLE
iCUE conflict

### ISSUE THREAD

**Issue by Noshei** [Kyusung4698/PoE-Overlay#460]
I use Corsair iCUE with my Corsair keyboard.  I have dedicated profiles for different applications, including PoE.  Since the latest update to PoE-Overlay (0.6.12) corsair iCUE no longer detects that PoE is the application with focus.

Prior to the 0.6.12 update, this would occur after opening the settings, and would require that I relaunch PoE-overlay for iCUE to detect PoE ad the application with focus.  Since the update, this does not work as a workaround.

If I relaunch PoE-Overlay, and go back into the game everything functions properly until I click outside of the game.  After which point iCUE will no longer register PoE as the window with focus.

Corsair iCUE is used to alter what keys on my keyboard do, so without it none of my custom keys on my keyboard function.

## 🌍  Your Environment
- OS: Win 10 x64 1903
- Version: 0.6.12
- PoE: Standalone

**Comment by MissingL-tter** [comment]
This is what I was talking about in issue #455 

> Without PoE Overlay Running:
>- App: PoE, Profile: PoE
>- Alt Tab
>- App: Desktop, Profile: Desktop
>- Click/Alt Tab/Refocus PoE
>- App: PoE, Profile: PoE
>
>With PoE Overlay Running:
>- App: PoE, Profile: PoE
>- Alt Tab
>- App: Desktop, Profile: Desktop
>- Click/Alt Tab/Refocus PoE
>- App: PoE, Profile: Desktop
>    - System does not recognize that PoE is the currently focused application
>    - The same thing happens if I open any of the overlay windows, basically any operation that causes PoE to lose focus

**Comment by bgriffs** [comment]
Can confirm the same issues on build 1909 as well.

🌍 Your Environment
OS: Win 10 x64 1909
Version: 0.6.12
PoE: Standalone

**Comment by OmikronGamma** [comment]
Same issue with Logitech software. Application detection kinda broken.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The new update 0.6.11 introduced keyboard support. In order to be able to support this i had to change my main window to be [focusable](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions). 

I'll provide a way of disabling this in the next version. Please keep in mind that this will also disable the keyboard support. There is no way to handle keyboard input without the (external) application having focus and therefore removing the focus of PoE. This is only possible if my application is injected into PoE - which is a planned feature but will take time to develop and get approved by GGG.

In the meantime i hope i can develop a way of only losing the focus once the dialog is open but this will also take some time because some refactoring is required.

Thanks again for giving me this important input! 

Best regards

**Comment by Noshei** [comment]
Please get the option for this ASAP, as it stands PoE-overlay is unusable for me.

**Comment by Kyusung4698** [comment]
## 0.6.13 (2020-03-25)

- add keyboard support toggle as tray menu entry (#460)
- update disable keyboard support by defaut (#460)
