### ISSUE TITLE
Random Crashes of PoE when using the overlay.

### ISSUE THREAD

**Issue by sunhallow** [Kyusung4698/PoE-Overlay#466]
I have noticed when using the PoE overlay. Poe crashes irregularly at complete random moments. I can't pin-point where it is exactly coming from or how to solve it at all.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. PoE Overlay does not interact with game itself (reading memory etc.) so a crash should be unlikely. I'll keep an open eye out. Also please fill out those missing information:

## 🌍  Your Environment

- OS: e.g. Win7 x64
- Version: e.g. 0.6.9 portable
- PoE: e.g. Steam 3.10.0/e English

**Comment by sunhallow** [comment]
OS : Win 10 X64
Version : 0.6.12 .exe install version
PoE : 3.10.0f English}

I have disabled hardware acceleration on the overlay now to see if that works better since i have had similar issues with it on different programs before. as you said it doesnt directly interact with the game itself so it might be something else.

**Comment by azarel41** [comment]
hi i just like to feedback that i share the same experience as him where i found out that poe overlay has been causing multiple crashes of my poe instance. i was previously experiencing 1 crash per map that i run (or even teleporting from safe house to town etc or alt - tabbing to check something on a browser) and this went away after i stopped running it. 

it probably happened after the prev GGG patch but ever since i stopped running poe overlay i have yet to experience a crash in 30 maps.

my details:

OS: e.g. Win10 x64
Version: e.g. 0.6.16
PoE: standalone 3.10.0/f English
