### ISSUE TITLE
Crush and whole pc unusable at that moment

### ISSUE THREAD

**Issue by Viridye** [Kyusung4698/PoE-Overlay#503]
When you are not using it and it is running in background, some times error popup and in that moment pc is unusable and it is even hard to click ok on error window

**Screenshots**
from event log
![image](https://user-images.githubusercontent.com/62805451/77827615-fd3bdf00-7116-11ea-8d16-a79ee586d6ca.png)

## 🌍  Your Environment
cpu: amd ryzen 3700x
gpu: nvidia gtx 1070
ram:  16gb hyperx 3600mhz
- OS: win 10 1909 Pro N 
- Version: 0.6.15.0
- PoE:  Steam 3.10.1b

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Iohook is required in order to capture the mousewheel input for the stash navigation feature. The latest updates removed the requiredness of running iohook all the time.  Therefore this issue should no longer occur that frequently. If this still occurs frequently you can disable the stash navigation to disable iohook.
