### ISSUE TITLE
Sometimes right click on the task tray icon doesn't work.

### ISSUE THREAD

**Issue by NITRO86sp** [Kyusung4698/PoE-Overlay#591]
Sometimes right click on the task tray icon doesn't work.

Right click on the task tray icon doesn't work. It only works if I double click and the settings window is open. Or another window or something.. But not when I alt tab..

- OS: Windows 10
- PoE: latest official

**Comment by Wiella** [comment]
Been having the same issues on both PCs I'm using (Windows 8.1 and Windows 10) since the early versions and up until now. 

Here is a guaranteed way to reproduce the issue for me under Windows 10:
- Press <kbd>WIN</kbd> button which prompts the Windows 10 menu
- Game is still visible (in windowed fullscreen), but I can also see the taskbar & tray
- Right click on the overlay icon in tray - it doesn't work

Once I tab out of the game and right click the overlay icon in the tray - it would sometimes prompt the windows task bar menu instead of the overlay menu. Second right click on the icon would then prompt the actual overlay menu.

Double-clicking the icon seem to work fine in all cases, but usually the only reason for me to open the tray menu in the first place is to reload overlay when it gets an update (to install it), going to the settings and finding the button there is slower and less convenient.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems to be a known Electron bug. There are currently no known fixes available. Please see following issue:

https://github.com/electron/electron/issues/12760
