### ISSUE TITLE
Game moving to background when using it

### ISSUE THREAD

**Issue by Cortex12341** [Kyusung4698/PoE-Overlay#623]
Hey
My game moves to background(the same way as if i would click the "-" on a windowed app, but im playing on fullscreen) if i try to check the price of an item, and once i close the item window, the game reopens.
Im using the latest version for windows 10, playing poe on steam.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Fullscreen is not supported. PoE must be in windowed or fullscreen windowed mode.

**Comment by Petusillos** [comment]
I'm having a similar issue since 0.6.19. PoE minimizes every time I use the tool. If I do an alt tab, PoE comes back to the front and after 1 second the overlay appears again in front of PoE, but as soon as I interact with the overlay (moving it, or just click part of the overlay), PoE is minimized again.

I'm using Windows 10 (Versión 10.0.18363.720), standalone PoE client (Windowed fullscreen / English), and as far I've tested, this does not happens if I close the application "Borderless Windows Helper 1.3". Everything was fine prior to 0.6.19 even when using that "Borderless Windows Helper 1.3"
Let me know pls if I should create a new issue or if you need further info or testing.
Thanks.

**Comment by Cortex12341** [comment]
Thanks for the support, that was indeed my problem!
Have changed the setting and forgot it was not supported. All working again!
