### ISSUE TITLE
Overlay causing accounts to get locked...

### ISSUE THREAD

**Issue by ThorTheGray** [Kyusung4698/PoE-Overlay#671]
This tool is causing accounts to get locked. See this [reddit thread](https://www.reddit.com/r/pathofexile/comments/ga0zlf/psa_waves_of_players_being_banned_for_use_of/). Just wanted to bring this to your attention since I didn't see the author respond there yet.

**Comment by AbeLincoln** [comment]
For reference, #426 added the debounce timer slider.

Maybe 0.5s is too short for the minimum and 1s is too short for the default.

Otherwise, there may be another set of actions which are causing 1 million failed requests in 24hr for users.

**Comment by Versalkul** [comment]
Ensuring to NOT hit the rate limit will fix bans from happening see [PoE WebDev response](https://www.reddit.com/r/pathofexile/comments/ga0zlf/psa_waves_of_players_being_banned_for_use_of/foxg9cj?utm_source=share&utm_medium=web2x)

**Comment by barbarolucente** [comment]
> 
> 
> For reference, #426 added the debounce timer slider.
> 
> Maybe 0.5s is too short for the minimum and 1s is too short for the default.


I've set mine on ∞ , still send the first though

**Comment by Xebtria** [comment]
as written in the other query, to prevent server flooding and risk of getting banned, the debounce timer should be a) ∞ by default and b) hard coded. not changable. every time you want to query, you need to actively press a button, only then the flooding of gggs servers is prevented and the risk of getting banned because of it is mitigated.

**Comment by Kyusung4698** [comment]
## 0.6.26 (2020-04-29)

- add enforce rate limit before calling the actual api
