### ISSUE TITLE
CTRL D should not automatically query the API

### ISSUE THREAD

**Issue by Juts2** [Kyusung4698/PoE-Overlay#672]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**
The app is making too many API calls, and most are useless. 

**Describe the solution you'd like**
Ctrl D should pull up the item UI is does now, but let you manually select and modify each affix before you click search. There is no reason to have it begin querying every time a single affix is selected or modified, or before any are chosen. There needs to be a manual search button. 

**Describe alternatives you've considered**

**Additional context**

**Comment by barbarolucente** [comment]
Exactly, 1 more click won't be that nightmare and maybe will stop trigger ggg.

**Comment by Xebtria** [comment]
completely agree, while it sure is QOL, the OG trade macro did not do that as far as I am concerened. you had to set your stats and your ranges, and then you had to click a button to get values. especially when you are still adjusting the ranges for some values, it basically queries every time, I can 100% see this being at least part of the issue that was caused.



I would suggest the following:
- if you have anything where there are no variables (currency, fragments, fossils, whatever), you can immediately query.
- if there is _anything_ which has variables (basically every equippable item with stats) it first opens, you have to set whatever stats and ranges, and then you have to press a button to do a query **once**. if you change anything, again it does not auto query, and you have to press a button manually to trigger the query again.

**Comment by caesarra2** [comment]
100% agree with the previous comments.

**Comment by niklaas-0rbit** [comment]
yeah, I also think that's one huge step the tool can make to reduce the amount of while we are not really loosing anything. Actually I think it's very unnecessary to directly sent the tradesearch-request since I always have to change some mods to get the actual search I want...

**Comment by Versalkul** [comment]
>     * if you have anything where there are no variables (currency, fragments, fossils, whatever), you can immediately query.

There is no need to query this, just get the price once an hour/day for all items from poe.ninja. They come in a nice json.  [Example!](https://poe.ninja/api/data/currencyoverview?league=Delirium&type=Currency) The price of currency and fragments tends to be stable!

**Comment by conetopia** [comment]
Some user like me prefer it this way, if you would like to make an additional command, thats cool. 
But not a replacement.

**Comment by Chuanhsing** [comment]
Set the “Debounce Time” in the settings “Evaluate/Query” to infinity (move the slider to the right).

**Comment by Xebtria** [comment]
> 
> 
> > ```
> > * if you have anything where there are no variables (currency, fragments, fossils, whatever), you can immediately query.
> > ```
> 
> There is no need to query this, just get the price once an hour/day for all items from poe.ninja. They come in a nice json. [Example!](https://poe.ninja/api/data/currencyoverview?league=Delirium&type=Currency) The price of currency and fragments tends to be stable!

disagree. even though they might not anymore, they can change very quickly and frequently, and especially so on league start, or maybe even during the league when a fancy video guide or clip to anything goes viral. I do not want the tool to show me outdated price. Especially if the currency quering hardly was the problem with poe overlay, it always was the problem that it almost instantly queries if you change a setting on the ranges. let it just work like the OG trade macro, change your settings, press a button manually to query once. and whatever you change, it does not query again unless you click the button again. Problem solved. usability goes down maybe like 1% but probability to get banned because of the tool goes down most likely by 100%.

> 
> 
> Set the “Debounce Time” in the settings “Evaluate/Query” to infinity (move the slider to the right).

this should be a) the default setting and b) not changeable. whether or not someone wouldn't like it if it is not changeable doesn't matter, because it is a requirement on the tool so the servers are not flooded with queries.

**Comment by Kyusung4698** [comment]
## 0.6.26 (2020-04-29)

- add initial search toggle - off by default (#672)
