### ISSUE TITLE
Literally not working after update 4/29/2020

### ISSUE THREAD

**Issue by poeplayer** [Kyusung4698/PoE-Overlay#674]
I ctr+D an item and the search will still come up but it will not show the prices of the item listed as normal.  I've tried this on many items.  Please fix this asap as I used this to price all my items!

**Comment by kartelusm** [comment]
If I could add to this, the behaviour is as described until you change something on the item, like add/remove attribute to the search or anything similar.

So yes, it is annoying and needs fixing, but there is a workaround at least :)

**Comment by poeplayer** [comment]
Yes I realized that if you click the search button it will search SOMETIMES. Most of the time, after changing changing / selecting a mod it will search but it is stuck there saying "found #.  Fetching # entries....Cancel?" then you click it and have to go to the browser every time you want to look at a different mod.
 if this stays this way I will have to use a different price app. :(

**Comment by conetopia** [comment]
Make sure you delete any/all older versions of POE-Overlay.
Open up pathofexile.com go to the trade tab, in that trade section, click clear cache.
Restart your computer, and then run a fresh new copy of POE-Overlay.
open game, click CTRL + D , then click the search, then boom ! Results :)
Seems to be the common issue for everyone, that the old stuff isn't being deleted properly.
also yes a new ( click search) feature has been added.
Because player accounts were being locked , because too many search requests blah blah blah.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The initial search is no longer run by default. This can be re-enabled at the settings menu. See screenshot below. 

![image](https://user-images.githubusercontent.com/38520678/80684489-09c0a800-8ac6-11ea-818b-88f9b151766c.png)

One of the biggest changes in this version was the enforcing of the ggg api rate limits. The overlay no longer tries to search for items if the current rate is exceeded and fail. Instead it will now wait until the rates are no longer exceeded. The longest wait can be up to 5 minutes. To improve this behavior you can try to lower your fetch count and set the debounce time to infinite and only search if all your mod adjustments have been made.
