### ISSUE TITLE
Suggestion: Account for Quality

### ISSUE THREAD

**Issue by egocarib** [Kyusung4698/PoE-Overlay#687]
# 🚀 feature request

When performing a search for an item that has additional quality crafted onto it, POE Overlay still limits me to searching at the maximum "normal" quality on the item (20%). For example, I'd like to search for helmets with >180 ES here, but the mouse wheel scroll wont go higher than 169, even though my helmet has 185 ES.

![image](https://user-images.githubusercontent.com/3429497/80892334-ccf3dd00-8c8e-11ea-9cf1-e2a1aec01c8a.png)

**Comment by conetopia** [comment]
I understand your trying to search for helmets, although those are Shields.
also yeah I have noticed the same thing when pricing rings/amulets/belts.

Had a hard time understanding why people kept spamming me instantly for some of my 20% quality items when i had set them for 10-25c... because normally it would cost up to 70chaos to 20% quality them lol. " they were decent average items "

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. With "Normalize Quality" enabled all properties affected are re-calculate with the default 20% max value. This can be disabled at the evaluate settings tab.
