### ISSUE TITLE
Black screen when using PoE-Overlay

### ISSUE THREAD

**Issue by Akalamiammiam51** [Kyusung4698/PoE-Overlay#722]
Hello there, 

Currently using Win10 and tried to use this overlay.
But I get a black screen once ingame, and I can only see the "PoE overlay 0.6.28" at the bottom left.
It seems to be triggered by alt-tabbing,but not sure.
Restarting from the taskbar does not change anything.
Quitting and restart manually does not either, black screen comes back as soon as I get back to PoE.

Run as admin, and tried a bunch of setups : 
All of the following give me the black screen
- Dx11 + Borderless
- Dx11 + Windowed + Borderless Gaming (https://github.com/Codeusa/Borderless-Gaming/releases)
- Vulkan + Windowed + Borderless Gaming 

As for the other setups
- Dx11 + Fullscreen : of course does not work very well, minimize PoE each time ctrl+D is used
- Dx11 + Windowed (without Borderless Gaming) : does not seem to cause black screen but it's horrendous.

- Vulkan + Borderless : Works, does not seems to cause black screen, but there is still a flickering each time the ctrl+D macro is used (for some reason, not when using crtl+mousewheel for stash tab navigation). Seems to be a common problem with other tools though so no surprise.
- Vulkan + Fullscreen : Same as for Dx11
- Vulkan + Windowed (without Borderless Gaming) : same as for Dx11

GPU driver is up to date (GTX 1070, driver version 446.14).

**Comment by yoinx** [comment]
I have my doubts that this is a POE Overlay issue, since it doesn't affect everyone.

I would recommend the following:
1. Check that your video card's refresh rate matches the monitor in the Nvidia control panel.
2. Double check that your power risers to you video card are seated well. Sometimes they can come loose and cause funkiness.
3. Use something like display driver uninstaller from guru3d to completely remove the Nvidia driver, then fresh install it. Sometimes with the updates they can get corrupted.

2 and 3 are admittedly a bit more extreme... But I think that your issue will be with number 1. The video card is likely glitching when switching between the desktop and the game because of a refresh rate issue. Since, I think, that the Overlay acts as a floating program over the game the same loses focus and throws it back to the desktop.

**Comment by Akalamiammiam51** [comment]
Ok so that was weird.

I checked the refresh rate on the NVidia control panel, everything was fine and setup for 60Hz.
However I also had Gsync activated, so out of curiosity, I tried to deactivate it which, for some reason, worked, no more black screen.

Then I tried to reactivqte Gsync and.... it kept working. So no idea what happen, but for now it seems ok.

Sadly Borderless Gaming + Windowed still cause flickering on Vulkan but I guess it's better to wait for a patch from GGG.

Thanks for you help anyway, your answer about refresh rate made me think of Gsync so that was probably the issue.

**Comment by yoinx** [comment]
You can use the AHK script that fixes this. POE Lurker also has a toggle now that lets you do vulkan fix. It lets you go windowed full screen without the issues on vulkan.

**Comment by Akalamiammiam51** [comment]
Tried PoE Lurker with Vulkan mode enablde but still get a flickering, both in Windowed and Borderless (and in Windowed I need to restart PoE Lurker a few times because sometimes it leave the taskbar on top).

I checked and I'm on the last version, so not sure what is the issue this time...

But maybe PoE Lurker repo is a better place to mention this.
