### ISSUE TITLE
Kicking players does not always work and chat will only be scanned while being the active window

### ISSUE THREAD

**Issue by Goldfield8** [Kyusung4698/PoE-Overlay#770]
Hey there!
Kicking players after trading with them does not always work. Pressing the button, where is says thanks and kicks them ends in a short framedrop in poe itself for me, which is probably the reason to not kicking them.

Some trade requests dont show up in poe overlay. Is there a reason for this to happen? Like having some other window active?

Apart from that, great tool!!

**Comment by Kyusung4698** [comment]
Hi, thank you for creating an issue. PoE Overlay scans the game log files in order to parse the chat message. If you filter the whisper from the game chat it will also stop logging those into the log files which would result in no trades being picked up. Also messages from Korean players are not logged for data privacy reasons. Those will also not end up at the UI. I've adjusted some timings in the latest version to hopefully prevent some commands from not triggering. But this may need some further adjustment.
