### ISSUE TITLE
No Icons, Text only

### ISSUE THREAD

**Issue by mushweed** [Kyusung4698/PoE-Overlay#805]
Hey,

I only see text, no icons in all menus...

![image](https://user-images.githubusercontent.com/24358061/88393303-b48eec80-cdbd-11ea-8668-fd16ad21e77a.png)

Any idea?

**Comment by Kyusung4698** [comment]
Hi, thanks for reporting this issue. In the past this was caused by an unhandled exception. 

So to help me narrow down the issue, can you please send me your Overwolf logs. See following topic on how to do so:
https://support.overwolf.com/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

Thanks!

**Comment by mushweed** [comment]
[OverwolfLogs_2020-08-02_21-31-52.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5012720/OverwolfLogs_2020-08-02_21-31-52.zip)

Hi, 

Overwolf Logs are attached.

Thanks!

**Comment by dmedlinger** [comment]
I also have this issue starting with the latest patch during heist league. Tried uninstalling + re-installing, no luck.

Uploading Overwolf logs.

[OverwolfLogs_2020-11-08_21-17-48.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5508283/OverwolfLogs_2020-11-08_21-17-48.zip)
