### ISSUE TITLE
Says cannot connect to the internet

### ISSUE THREAD

**Issue by BryantDavis1986** [Kyusung4698/PoE-Overlay#836]
# 🐞 bug report

**Describe the bug**
when i downloaded the installer and tried to run it, it says I need to connect to the internet. I was in poe playing and on discord. So i tried closing poe thinking that was the issue but was still getting the same issue. 

**To Reproduce**

**Screenshots**

![image](https://user-images.githubusercontent.com/62255879/93891328-28efea00-fca0-11ea-82fa-2b434aae5c66.png)

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. After the first installation a request is made to the PoE Api to get the current leagues. So this is normally caused by an unavailable Api. Therefore can you please check if this is still an issue?

In case it's still not working please send me your application logs so i can further investigate this issue. See following topic on how to generate them:
https://support.overwolf.com/en/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

Thanks! 🚀

**Comment by BryantDavis1986** [comment]
> Hi, thanks for creating an issue. After the first installation a request is made to the PoE Api to get the current leagues. So this is normally caused by an unavailable Api. Therefore can you please check if this is still an issue?
> 
> In case it's still not working please send me your application logs so i can further investigate this issue. See following topic on how to generate them:
> https://support.overwolf.com/en/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs
> 
> Thanks! 🚀

I got it working, was an overwolf issue, the error is because i guess its unable to install while having a firewall. not a very clear error on their part
